import { createContext, useContext, useState, ReactNode } from 'react';
import { Language } from '../types';

// ── Translations ──────────────────────────────────────────────────────────────

const translations = {
  en: {
    // Nav
    nav_home: 'Home',
    nav_problems: 'Problems',
    nav_about: 'About',
    nav_add: 'Add Problem',
    nav_signout: 'Sign Out',
    nav_admin: 'Admin',

    // Home
    home_eyebrow: 'Kazakhstan Experimental Physics Olympiad',
    home_hero_title_1: 'Master the Art of',
    home_hero_title_2: 'Experimental Physics',
    home_hero_desc: 'A curated archive of experimental physics problems from KazEPhO, Respa, and IZhO — with full LaTeX solutions, methodology, and experimental setups.',
    home_cta_browse: 'Browse Problems',
    home_cta_learn: 'Learn More',
    home_stat_problems: 'Problems',
    home_stat_olympiads: 'Olympiads',
    home_stat_students: 'Students',
    home_featured: 'Featured Problems',
    home_view_all: 'View All Problems',
    home_olympiad_title: 'The Olympiads',
    home_olympiad_desc_kazepho: 'The flagship national competition. Original problems designed by Kazakhstani educators.',
    home_olympiad_desc_respa: 'Republic-level competition covering a broad range of physics for grades 8–11.',
    home_olympiad_desc_izho: 'International competition hosted in Almaty, known for its challenging experimental rounds.',
    home_browse: 'Browse',

    // Problems page
    problems_title: 'Problems Archive',
    problems_subtitle: 'Browse experimental physics problems. Press',
    problems_subtitle2: 'to search.',
    problems_empty_title: 'No problems found',
    problems_empty_desc: 'Try adjusting your filters or search term.',
    problems_clear_filters: 'Clear all filters',

    // Filter bar
    filter_search_placeholder: 'Search by title or topic…',
    filter_results: 'result',
    filter_results_plural: 'results',
    filter_clear_all: 'Clear all',
    filter_olympiad: 'Olympiad',
    filter_difficulty: 'Difficulty',
    filter_year: 'Year',
    filter_grade: 'Grade',
    filter_all: 'All',
    filter_all_years: 'All years',
    filter_all_grades: 'All grades',

    // Problem detail
    detail_all_problems: 'All Problems',
    detail_print: 'Print / Save PDF',
    detail_download_pdf: 'Download PDF',
    detail_share: 'Share',
    detail_copied: '✓ Copied!',
    detail_edit: 'Edit',
    detail_delete: 'Delete',
    detail_deleting: 'Deleting…',
    detail_statement: 'Problem Statement',
    detail_setup: 'Experimental Setup',
    detail_solution: 'Full Solution',
    detail_reveal: 'Reveal Solution',
    detail_hide: 'Hide Solution',
    detail_info: 'Problem Info',
    detail_olympiad: 'Olympiad',
    detail_year: 'Year',
    detail_difficulty: 'Difficulty',
    detail_grade: 'Grade',
    detail_topics: 'Topics',
    detail_language: 'Language',
    detail_more_from: 'More from',
    detail_not_found_title: 'Problem Not Found',
    detail_not_found_desc: "This problem doesn't exist or may have been removed.",
    detail_browse_all: 'Browse All Problems',
    detail_go_back: 'Go Back',
    detail_delete_confirm: 'Delete this problem permanently?',

    // Add/Edit problem
    add_title: 'Add New Problem',
    edit_title: 'Edit Problem',
    add_breadcrumb: 'Add Problem',
    edit_breadcrumb: 'Edit Problem',
    form_details: 'Problem Details',
    form_title_label: 'Title',
    form_title_placeholder: 'e.g., Measuring Speed of Sound',
    form_olympiad: 'Olympiad',
    form_add_olympiad: 'Add',
    form_cancel_olympiad: 'Cancel',
    form_olympiad_placeholder: 'e.g., Zhautykov',
    form_year: 'Year',
    form_grade: 'Grade',
    form_grade_na: 'N/A',
    form_difficulty: 'Difficulty',
    form_tags: 'Tags (comma-separated)',
    form_tags_placeholder: 'optics, waves, measurement',
    form_language: 'Problem Language',
    form_pdf: 'Upload PDF',
    form_pdf_hint: 'Upload a PDF version of this problem for download.',
    form_pdf_uploaded: 'PDF uploaded',
    form_pdf_remove: 'Remove',
    form_statement: 'Problem Statement',
    form_setup: 'Experimental Setup',
    form_solution: 'Full Solution',
    form_cancel: 'Cancel',
    form_save: 'Save Changes',
    form_add: 'Add Problem',
    form_saving: 'Saving…',
    form_saved: 'Changes saved!',
    form_added: 'Problem added!',
    form_redirecting: 'Redirecting…',
    form_unauthorized_title: 'Admin Access Required',
    form_unauthorized_desc: 'You must be signed in as an admin to manage problems.',
    form_sign_in: 'Sign In as Admin',
    editor_tip: 'Tip: Use',
    editor_tip2: 'for inline math,',
    editor_tip3: 'for display equations',
    editor_upload_image: 'Upload Image',
    editor_uploading: 'Uploading…',

    // About
    about_title: 'About KazEPhO',
    about_subtitle: 'Preserving and sharing experimental physics knowledge across Kazakhstan.',
    about_mission: 'Our Mission',
    about_mission_text: 'KazEPhO is a platform dedicated to making experimental physics problems accessible to all students. We archive problems from the most prestigious Kazakhstani and international olympiads.',
    about_olympiad_title: 'The Olympiads',
    about_history: 'History',
    about_platform: 'The Platform',
    about_platform_text: 'Built to be a living archive — problems can be updated, solutions refined, and new content added without touching the source code.',

    // Login
    login_title: 'Admin Access',
    login_subtitle: 'Enter the admin password to manage problems.',
    login_password: 'Password',
    login_show: 'Show password',
    login_hide: 'Hide password',
    login_submit: 'Sign In',
    login_signing: 'Signing in…',
    login_error: 'Incorrect password. Please try again.',
    login_back: '← Back to site',

    // Language names
    lang_en: 'English',
    lang_ru: 'Русский',
    lang_kz: 'Қазақша',

    // Language badge
    lang_badge_en: 'EN',
    lang_badge_ru: 'RU',
    lang_badge_kz: 'KZ',

    // Home — olympiad info
    home_kazepho_full: 'Kazakhstan Experimental Physics Olympiad',
    home_respa_full: 'Republican Physics Olympiad',
    home_izho_full: 'International Zhautykov Olympiad',
    home_kazepho_desc: 'The flagship national competition. Original problems designed by Kazakhstani educators.',
    home_respa_desc: 'Republic-level competition covering a broad range of physics for grades 8–11.',
    home_izho_desc: 'International competition hosted in Almaty, known for its challenging experimental rounds.',
    home_explore_problems: 'Explore problems',
    home_section_sources: 'Problem Sources',
    home_section_sources_sub: 'Three major Kazakhstan physics competitions, all in one place.',
    home_section_recent: 'Recent Problems',
    home_view_all_link: 'View all',
    home_empty_problems: 'No problems yet.',
    home_empty_add: 'Add the first one →',

    // NotFound
    notfound_code: '404',
    notfound_title: 'Page Not Found',
    notfound_desc: "This page doesn't exist or may have been moved. Let's get you back on track.",
    notfound_go_home: 'Go Home',
    notfound_browse: 'Browse Problems',
    notfound_go_back: 'Go Back',
    notfound_try: 'Or try one of these:',
    notfound_kazepho: 'KazEPhO Problems',
    notfound_izho: 'IZhO Problems',
    notfound_hard: 'Hard Problems',

    // About
    about_eyebrow: 'About KazEPhO Archive',
    about_hero_1: "Preserving Kazakhstan's Physics",
    about_hero_2: 'Olympiad Heritage',
    about_hero_desc: "A free, open archive of experimental physics problems from Kazakhstan's top olympiads — built for students, teachers, and physics enthusiasts.",
    about_stat_olympiads: 'Olympiads covered',
    about_stat_years: 'Years of problems',
    about_stat_free: 'Free for all students',
    about_stat_platform: 'Archive platform',
    about_mission_p1: 'Experimental physics olympiads develop a rare set of skills — the ability to design experiments, handle real equipment, estimate uncertainties, and communicate findings clearly. These are skills that textbooks alone cannot teach.',
    about_mission_p2: 'Yet the problems from these competitions were largely scattered, lost after each olympiad season, or accessible only to a select few. This archive exists to change that — making every problem, solution, and methodology freely available to any student in Kazakhstan and beyond.',
    about_browse_problems: 'Browse Problems',
    about_for_students: 'For Students',
    about_for_students_desc: 'Practice with real olympiad problems, study full solutions, and understand experimental methodology.',
    about_for_teachers: 'For Teachers',
    about_for_teachers_desc: 'Find problems by topic, difficulty, and grade level. Use as teaching material or competition preparation.',
    about_for_organizers: 'For Organizers',
    about_for_organizers_desc: 'Reference historical problems to avoid repetition and maintain the high standard of Kazakhstani olympiads.',
    about_kazepho_desc: 'The flagship national experimental physics competition. Problems are designed by Kazakhstani educators and focus on hands-on experimental methodology, measurement uncertainty, and physical intuition.',
    about_respa_desc: 'The republic-level competition covering both theoretical and experimental physics for grades 8–11. Serves as a qualifier for international competitions.',
    about_izho_desc: 'An international competition hosted annually in Almaty. Known for its challenging experimental rounds and attracts participants from over 30 countries.',
    about_view_problems: 'View problems',
    about_timeline_1: 'KazEPhO founded in Almaty by a group of physics educators.',
    about_timeline_2: 'First official olympiad held with 120 participants from 12 regions.',
    about_timeline_3: 'Partnership established with IZhO organizing committee.',
    about_timeline_4: 'Archive project launched to preserve and share problems digitally.',
    about_cta_title: 'Start Exploring',
    about_cta_desc: 'Browse the full archive of experimental physics problems.',
    about_cta_btn: 'View All Problems',

    // Footer
    footer_tagline: 'Advancing experimental physics education in Kazakhstan.',
    footer_problems: 'Problems Archive',
    footer_copy: 'Kazakhstan Experimental Physics Olympiad',

    // Small component strings
    grade_prefix: 'Grade',
    card_view: 'View Problem & Solution',
    form_already_exists: 'Already exists.',
    form_tab_edit: 'Edit',
    form_tab_preview: 'Preview',
    form_lang_hint: 'Fill in content for each language separately',
    form_untitled: 'Untitled Problem',
    form_no_content: 'No content yet…',
    form_back_editor: '← Back to Editor',
    form_remove_name: 'Remove',
  },

  ru: {
    nav_home: 'Главная',
    nav_problems: 'Задачи',
    nav_about: 'О проекте',
    nav_add: 'Добавить задачу',
    nav_signout: 'Выйти',
    nav_admin: 'Войти',

    home_eyebrow: 'Казахстанская Олимпиада по Экспериментальной Физике',
    home_hero_title_1: 'Овладейте искусством',
    home_hero_title_2: 'Экспериментальной Физики',
    home_hero_desc: 'Архив задач по экспериментальной физике из KazEPhO, Respa и ИЖО — с полными решениями на LaTeX, методологией и описаниями установок.',
    home_cta_browse: 'Смотреть задачи',
    home_cta_learn: 'Узнать больше',
    home_stat_problems: 'Задачи',
    home_stat_olympiads: 'Олимпиады',
    home_stat_students: 'Ученики',
    home_featured: 'Избранные задачи',
    home_view_all: 'Все задачи',
    home_olympiad_title: 'Олимпиады',
    home_olympiad_desc_kazepho: 'Главная национальная олимпиада. Оригинальные задачи казахстанских педагогов.',
    home_olympiad_desc_respa: 'Республиканская олимпиада по физике для 8–11 классов.',
    home_olympiad_desc_izho: 'Международная олимпиада в Алматы с известными экспериментальными турами.',
    home_browse: 'Смотреть',

    problems_title: 'Архив задач',
    problems_subtitle: 'Просматривайте задачи. Нажмите',
    problems_subtitle2: 'для поиска.',
    problems_empty_title: 'Задачи не найдены',
    problems_empty_desc: 'Попробуйте изменить фильтры или поисковый запрос.',
    problems_clear_filters: 'Сбросить фильтры',

    filter_search_placeholder: 'Поиск по названию или теме…',
    filter_results: 'результат',
    filter_results_plural: 'результатов',
    filter_clear_all: 'Сбросить',
    filter_olympiad: 'Олимпиада',
    filter_difficulty: 'Сложность',
    filter_year: 'Год',
    filter_grade: 'Класс',
    filter_all: 'Все',
    filter_all_years: 'Все годы',
    filter_all_grades: 'Все классы',

    detail_all_problems: 'Все задачи',
    detail_print: 'Печать / PDF',
    detail_download_pdf: 'Скачать PDF',
    detail_share: 'Поделиться',
    detail_copied: '✓ Скопировано!',
    detail_edit: 'Редактировать',
    detail_delete: 'Удалить',
    detail_deleting: 'Удаление…',
    detail_statement: 'Условие задачи',
    detail_setup: 'Экспериментальная установка',
    detail_solution: 'Полное решение',
    detail_reveal: 'Показать решение',
    detail_hide: 'Скрыть решение',
    detail_info: 'Информация о задаче',
    detail_olympiad: 'Олимпиада',
    detail_year: 'Год',
    detail_difficulty: 'Сложность',
    detail_grade: 'Класс',
    detail_topics: 'Темы',
    detail_language: 'Язык',
    detail_more_from: 'Ещё из',
    detail_not_found_title: 'Задача не найдена',
    detail_not_found_desc: 'Эта задача не существует или была удалена.',
    detail_browse_all: 'Все задачи',
    detail_go_back: 'Назад',
    detail_delete_confirm: 'Удалить задачу навсегда?',

    add_title: 'Добавить задачу',
    edit_title: 'Редактировать задачу',
    add_breadcrumb: 'Добавить задачу',
    edit_breadcrumb: 'Редактировать',
    form_details: 'Детали задачи',
    form_title_label: 'Название',
    form_title_placeholder: 'напр., Измерение скорости звука',
    form_olympiad: 'Олимпиада',
    form_add_olympiad: 'Добавить',
    form_cancel_olympiad: 'Отмена',
    form_olympiad_placeholder: 'напр., Жауытыков',
    form_year: 'Год',
    form_grade: 'Класс',
    form_grade_na: 'Н/П',
    form_difficulty: 'Сложность',
    form_tags: 'Теги (через запятую)',
    form_tags_placeholder: 'оптика, волны, измерения',
    form_language: 'Язык задачи',
    form_pdf: 'Загрузить PDF',
    form_pdf_hint: 'Загрузите PDF-версию задачи для скачивания.',
    form_pdf_uploaded: 'PDF загружен',
    form_pdf_remove: 'Удалить',
    form_statement: 'Условие задачи',
    form_setup: 'Экспериментальная установка',
    form_solution: 'Полное решение',
    form_cancel: 'Отмена',
    form_save: 'Сохранить',
    form_add: 'Добавить задачу',
    form_saving: 'Сохранение…',
    form_saved: 'Изменения сохранены!',
    form_added: 'Задача добавлена!',
    form_redirecting: 'Перенаправление…',
    form_unauthorized_title: 'Требуется доступ администратора',
    form_unauthorized_desc: 'Вы должны войти как администратор для управления задачами.',
    form_sign_in: 'Войти как администратор',
    editor_tip: 'Подсказка: используйте',
    editor_tip2: 'для инлайн-формул,',
    editor_tip3: 'для блочных формул',
    editor_upload_image: 'Загрузить изображение',
    editor_uploading: 'Загрузка…',

    about_title: 'О KazEPhO',
    about_subtitle: 'Сохранение и распространение знаний по экспериментальной физике в Казахстане.',
    about_mission: 'Наша миссия',
    about_mission_text: 'KazEPhO — платформа для доступа к задачам по экспериментальной физике для всех учеников. Мы архивируем задачи из самых престижных казахстанских и международных олимпиад.',
    about_olympiad_title: 'Олимпиады',
    about_history: 'История',
    about_platform: 'Платформа',
    about_platform_text: 'Создана как живой архив — задачи можно обновлять, решения улучшать, а новый контент добавлять без изменения исходного кода.',

    login_title: 'Вход для администратора',
    login_subtitle: 'Введите пароль администратора для управления задачами.',
    login_password: 'Пароль',
    login_show: 'Показать пароль',
    login_hide: 'Скрыть пароль',
    login_submit: 'Войти',
    login_signing: 'Вход…',
    login_error: 'Неверный пароль. Попробуйте ещё раз.',
    login_back: '← На сайт',

    lang_en: 'English',
    lang_ru: 'Русский',
    lang_kz: 'Қазақша',
    lang_badge_en: 'EN',
    lang_badge_ru: 'RU',
    lang_badge_kz: 'KZ',

    home_kazepho_full: 'Казахстанская олимпиада по экспериментальной физике',
    home_respa_full: 'Республиканская олимпиада по физике',
    home_izho_full: 'Международная Жаутыковская олимпиада',
    home_kazepho_desc: 'Главная национальная олимпиада. Оригинальные задачи казахстанских педагогов.',
    home_respa_desc: 'Республиканская олимпиада по физике для 8–11 классов.',
    home_izho_desc: 'Международная олимпиада в Алматы с известными экспериментальными турами.',
    home_explore_problems: 'Смотреть задачи',
    home_section_sources: 'Источники задач',
    home_section_sources_sub: 'Три крупнейшие казахстанские физические олимпиады в одном месте.',
    home_section_recent: 'Последние задачи',
    home_view_all_link: 'Смотреть все',
    home_empty_problems: 'Задач пока нет.',
    home_empty_add: 'Добавить первую →',

    notfound_code: '404',
    notfound_title: 'Страница не найдена',
    notfound_desc: 'Эта страница не существует или была перемещена.',
    notfound_go_home: 'На главную',
    notfound_browse: 'Смотреть задачи',
    notfound_go_back: 'Назад',
    notfound_try: 'Или попробуйте:',
    notfound_kazepho: 'Задачи KazEPhO',
    notfound_izho: 'Задачи IZhO',
    notfound_hard: 'Сложные задачи',

    about_eyebrow: 'Об архиве KazEPhO',
    about_hero_1: 'Сохраняем наследие',
    about_hero_2: 'Физических олимпиад Казахстана',
    about_hero_desc: 'Бесплатный открытый архив задач по экспериментальной физике из лучших олимпиад Казахстана — для учеников, учителей и энтузиастов физики.',
    about_stat_olympiads: 'Олимпиад охвачено',
    about_stat_years: 'Лет задач',
    about_stat_free: 'Бесплатно для всех',
    about_stat_platform: 'Платформа архива',
    about_mission_p1: 'Олимпиады по экспериментальной физике развивают редкие навыки — умение проектировать эксперименты, работать с реальным оборудованием, оценивать погрешности и ясно излагать результаты. Этому не научат одни учебники.',
    about_mission_p2: 'Однако задачи этих соревнований были разбросаны, терялись после каждого сезона или были доступны лишь избранным. Этот архив создан, чтобы изменить это — сделать каждую задачу, решение и методологию свободно доступными для любого ученика.',
    about_browse_problems: 'Смотреть задачи',
    about_for_students: 'Для учеников',
    about_for_students_desc: 'Практикуйтесь с реальными олимпиадными задачами, изучайте полные решения и понимайте экспериментальную методологию.',
    about_for_teachers: 'Для учителей',
    about_for_teachers_desc: 'Находите задачи по теме, сложности и классу. Используйте как учебный материал или подготовку к олимпиадам.',
    about_for_organizers: 'Для организаторов',
    about_for_organizers_desc: 'Используйте архив задач, чтобы избежать повторений и поддерживать высокий уровень казахстанских олимпиад.',
    about_kazepho_desc: 'Главная национальная олимпиада по экспериментальной физике. Задачи разработаны казахстанскими педагогами и сфокусированы на экспериментальной методологии, оценке погрешностей и физической интуиции.',
    about_respa_desc: 'Республиканская олимпиада по теоретической и экспериментальной физике для 8–11 классов. Служит отбором на международные олимпиады.',
    about_izho_desc: 'Международная олимпиада, ежегодно проводимая в Алматы. Известна сложными экспериментальными турами и привлекает участников из более чем 30 стран.',
    about_view_problems: 'Смотреть задачи',
    about_timeline_1: 'KazEPhO основан в Алматы группой преподавателей физики.',
    about_timeline_2: 'Первая официальная олимпиада: 120 участников из 12 регионов.',
    about_timeline_3: 'Установлено партнёрство с оргкомитетом IZhO.',
    about_timeline_4: 'Запущен проект архива для цифрового сохранения задач.',
    about_cta_title: 'Начните исследовать',
    about_cta_desc: 'Просматривайте полный архив задач по экспериментальной физике.',
    about_cta_btn: 'Все задачи',

    footer_tagline: 'Развитие образования по экспериментальной физике в Казахстане.',
    footer_problems: 'Архив задач',
    footer_copy: 'Казахстанская олимпиада по экспериментальной физике',

    grade_prefix: 'Класс',
    card_view: 'Смотреть задачу и решение',
    form_already_exists: 'Уже существует.',
    form_tab_edit: 'Редактировать',
    form_tab_preview: 'Предпросмотр',
    form_lang_hint: 'Заполните контент для каждого языка отдельно',
    form_untitled: 'Без названия',
    form_no_content: 'Контент пока не добавлен…',
    form_back_editor: '← Назад к редактору',
    form_remove_name: 'Удалить',
  },

  kz: {
    nav_home: 'Басты бет',
    nav_problems: 'Есептер',
    nav_about: 'Жоба туралы',
    nav_add: 'Есеп қосу',
    nav_signout: 'Шығу',
    nav_admin: 'Кіру',

    home_eyebrow: 'Қазақстандық Эксперименталдық Физика Олимпиадасы',
    home_hero_title_1: 'Өнерін меңгеріңіз',
    home_hero_title_2: 'Эксперименталдық Физика',
    home_hero_desc: 'KazEPhO, Respa және ЖОлимпиадаларынан эксперименталдық физика есептерінің мұрағаты — толық LaTeX шешімдерімен, әдістемемен және тәжірибелік орнатулармен.',
    home_cta_browse: 'Есептерді қарау',
    home_cta_learn: 'Толығырақ',
    home_stat_problems: 'Есептер',
    home_stat_olympiads: 'Олимпиадалар',
    home_stat_students: 'Оқушылар',
    home_featured: 'Таңдаулы есептер',
    home_view_all: 'Барлық есептер',
    home_olympiad_title: 'Олимпиадалар',
    home_olympiad_desc_kazepho: 'Негізгі ұлттық олимпиада. Қазақстандық педагогтардың түпнұсқа есептері.',
    home_olympiad_desc_respa: '8–11 сынып оқушылары үшін республикалық физика олимпиадасы.',
    home_olympiad_desc_izho: 'Алматыда өтетін халықаралық олимпиада, тәжірибелік турлармен белгілі.',
    home_browse: 'Қарау',

    problems_title: 'Есептер мұрағаты',
    problems_subtitle: 'Есептерді қараңыз. Іздеу үшін',
    problems_subtitle2: 'басыңыз.',
    problems_empty_title: 'Есептер табылмады',
    problems_empty_desc: 'Сүзгілерді немесе іздеу сұрауын өзгертіп көріңіз.',
    problems_clear_filters: 'Сүзгілерді тазалау',

    filter_search_placeholder: 'Тақырып немесе тақырыбы бойынша іздеу…',
    filter_results: 'нәтиже',
    filter_results_plural: 'нәтиже',
    filter_clear_all: 'Тазалау',
    filter_olympiad: 'Олимпиада',
    filter_difficulty: 'Қиындық',
    filter_year: 'Жыл',
    filter_grade: 'Сынып',
    filter_all: 'Барлығы',
    filter_all_years: 'Барлық жылдар',
    filter_all_grades: 'Барлық сыныптар',

    detail_all_problems: 'Барлық есептер',
    detail_print: 'Басып шығару / PDF',
    detail_download_pdf: 'PDF жүктеу',
    detail_share: 'Бөлісу',
    detail_copied: '✓ Көшірілді!',
    detail_edit: 'Өңдеу',
    detail_delete: 'Жою',
    detail_deleting: 'Жойылуда…',
    detail_statement: 'Есеп шарты',
    detail_setup: 'Тәжірибелік орнату',
    detail_solution: 'Толық шешім',
    detail_reveal: 'Шешімді көрсету',
    detail_hide: 'Шешімді жасыру',
    detail_info: 'Есеп туралы ақпарат',
    detail_olympiad: 'Олимпиада',
    detail_year: 'Жыл',
    detail_difficulty: 'Қиындық',
    detail_grade: 'Сынып',
    detail_topics: 'Тақырыптар',
    detail_language: 'Тіл',
    detail_more_from: 'Қосымша:',
    detail_not_found_title: 'Есеп табылмады',
    detail_not_found_desc: 'Бұл есеп жоқ немесе жойылған болуы мүмкін.',
    detail_browse_all: 'Барлық есептер',
    detail_go_back: 'Артқа',
    detail_delete_confirm: 'Есепті біржолата жою керек пе?',

    add_title: 'Жаңа есеп қосу',
    edit_title: 'Есепті өңдеу',
    add_breadcrumb: 'Есеп қосу',
    edit_breadcrumb: 'Өңдеу',
    form_details: 'Есеп мәліметтері',
    form_title_label: 'Атауы',
    form_title_placeholder: 'мыс., Дыбыс жылдамдығын өлшеу',
    form_olympiad: 'Олимпиада',
    form_add_olympiad: 'Қосу',
    form_cancel_olympiad: 'Болдырмау',
    form_olympiad_placeholder: 'мыс., Жауытыков',
    form_year: 'Жыл',
    form_grade: 'Сынып',
    form_grade_na: 'Жоқ',
    form_difficulty: 'Қиындық',
    form_tags: 'Тегтер (үтірмен бөлінген)',
    form_tags_placeholder: 'оптика, толқындар, өлшем',
    form_language: 'Есеп тілі',
    form_pdf: 'PDF жүктеу',
    form_pdf_hint: 'Есептің PDF нұсқасын жүктеңіз.',
    form_pdf_uploaded: 'PDF жүктелді',
    form_pdf_remove: 'Жою',
    form_statement: 'Есеп шарты',
    form_setup: 'Тәжірибелік орнату',
    form_solution: 'Толық шешім',
    form_cancel: 'Болдырмау',
    form_save: 'Сақтау',
    form_add: 'Есеп қосу',
    form_saving: 'Сақталуда…',
    form_saved: 'Өзгерістер сақталды!',
    form_added: 'Есеп қосылды!',
    form_redirecting: 'Бағытталуда…',
    form_unauthorized_title: 'Әкімші рұқсаты қажет',
    form_unauthorized_desc: 'Есептерді басқару үшін әкімші ретінде кіруіңіз керек.',
    form_sign_in: 'Әкімші ретінде кіру',
    editor_tip: 'Кеңес:',
    editor_tip2: 'инлайн формула үшін,',
    editor_tip3: 'блок формула үшін',
    editor_upload_image: 'Сурет жүктеу',
    editor_uploading: 'Жүктелуде…',

    about_title: 'KazEPhO туралы',
    about_subtitle: 'Қазақстандағы эксперименталдық физика білімін сақтау және тарату.',
    about_mission: 'Біздің миссия',
    about_mission_text: 'KazEPhO — барлық оқушыларға эксперименталдық физика есептерін қолжетімді ету платформасы.',
    about_olympiad_title: 'Олимпиадалар',
    about_history: 'Тарих',
    about_platform: 'Платформа',
    about_platform_text: 'Тірі мұрағат ретінде жасалған — бастапқы кодты өзгертпестен есептерді жаңартуға болады.',

    login_title: 'Әкімші кірісі',
    login_subtitle: 'Есептерді басқару үшін әкімші құпия сөзін енгізіңіз.',
    login_password: 'Құпия сөз',
    login_show: 'Құпия сөзді көрсету',
    login_hide: 'Жасыру',
    login_submit: 'Кіру',
    login_signing: 'Кіруде…',
    login_error: 'Қате құпия сөз. Қайтадан көріңіз.',
    login_back: '← Сайтқа',

    lang_en: 'English',
    lang_ru: 'Русский',
    lang_kz: 'Қазақша',
    lang_badge_en: 'EN',
    lang_badge_ru: 'RU',
    lang_badge_kz: 'KZ',

    home_kazepho_full: 'Қазақстандық эксперименталдық физика олимпиадасы',
    home_respa_full: 'Республикалық физика олимпиадасы',
    home_izho_full: 'Халықаралық Жаутыков олимпиадасы',
    home_kazepho_desc: 'Негізгі ұлттық олимпиада. Қазақстандық педагогтардың түпнұсқа есептері.',
    home_respa_desc: '8–11 сынып оқушылары үшін республикалық физика олимпиадасы.',
    home_izho_desc: 'Алматыда өтетін халықаралық олимпиада, тәжірибелік турлармен белгілі.',
    home_explore_problems: 'Есептерді қарау',
    home_section_sources: 'Есеп көздері',
    home_section_sources_sub: 'Үш негізгі қазақстандық физика олимпиадасы бір жерде.',
    home_section_recent: 'Соңғы есептер',
    home_view_all_link: 'Барлығын қарау',
    home_empty_problems: 'Есептер әлі жоқ.',
    home_empty_add: 'Біріншісін қосу →',

    notfound_code: '404',
    notfound_title: 'Бет табылмады',
    notfound_desc: 'Бұл бет жоқ немесе жылжытылған болуы мүмкін.',
    notfound_go_home: 'Басты бетке',
    notfound_browse: 'Есептерді қарау',
    notfound_go_back: 'Артқа',
    notfound_try: 'Немесе мынаны көріңіз:',
    notfound_kazepho: 'KazEPhO есептері',
    notfound_izho: 'IZhO есептері',
    notfound_hard: 'Қиын есептер',

    about_eyebrow: 'KazEPhO мұрағаты туралы',
    about_hero_1: 'Қазақстанның физика',
    about_hero_2: 'олимпиада мұрасын сақтаймыз',
    about_hero_desc: 'Қазақстанның үздік олимпиадаларынан эксперименталдық физика есептерінің тегін ашық мұрағаты — оқушылар, мұғалімдер және физика әуесқойлары үшін.',
    about_stat_olympiads: 'Олимпиадалар қамтылды',
    about_stat_years: 'Жыл есептері',
    about_stat_free: 'Барлығына тегін',
    about_stat_platform: 'Мұрағат платформасы',
    about_mission_p1: 'Эксперименталдық физика олимпиадалары сирек дағдыларды дамытады — эксперимент жоспарлау, нақты құрал-жабдықпен жұмыс істеу, қателіктерді бағалау және нәтижелерді анық баяндау. Бұл дағдыларды тек оқулықтардан үйрену мүмкін емес.',
    about_mission_p2: 'Бірақ бұл жарыстардың есептері шашылып, маусым сайын жоғалып немесе аз адамға ғана қолжетімді болатын. Бұл мұрағат мұны өзгерту үшін жасалған — әрбір есепті, шешімді және әдістемені Қазақстандағы кез келген оқушыға тегін қолжетімді ету.',
    about_browse_problems: 'Есептерді қарау',
    about_for_students: 'Оқушылар үшін',
    about_for_students_desc: 'Нақты олимпиада есептерімен жаттығыңыз, толық шешімдерді зерттеңіз және эксперименталдық әдістемені түсініңіз.',
    about_for_teachers: 'Мұғалімдер үшін',
    about_for_teachers_desc: 'Есептерді тақырып, қиындық және сынып бойынша табыңыз. Оқу материалы немесе олимпиадаға дайындық ретінде қолданыңыз.',
    about_for_organizers: 'Ұйымдастырушылар үшін',
    about_for_organizers_desc: 'Қайталаудан аулақ болу және қазақстандық олимпиадалардың жоғары деңгейін сақтау үшін тарихи есептерге сілтеме жасаңыз.',
    about_kazepho_desc: 'Негізгі ұлттық эксперименталдық физика олимпиадасы. Есептер қазақстандық педагогтармен жасалған және эксперименталдық әдістемеге, өлшем қателігіне және физикалық интуицияға бағытталған.',
    about_respa_desc: '8–11 сынып оқушылары үшін теориялық және эксперименталдық физика бойынша республикалық олимпиада. Халықаралық олимпиадаларға іріктеу ретінде қызмет етеді.',
    about_izho_desc: 'Алматыда жыл сайын өтетін халықаралық олимпиада. Күрделі тәжірибелік турларымен белгілі және 30-дан астам елден қатысушыларды тартады.',
    about_view_problems: 'Есептерді қарау',
    about_timeline_1: 'KazEPhO Алматыда физика оқытушылар тобымен құрылды.',
    about_timeline_2: 'Бірінші ресми олимпиада: 12 аймақтан 120 қатысушы.',
    about_timeline_3: 'IZhO ұйымдастыру комитетімен серіктестік орнатылды.',
    about_timeline_4: 'Есептерді сандық сақтау үшін мұрағат жобасы іске қосылды.',
    about_cta_title: 'Зерттеуді бастаңыз',
    about_cta_desc: 'Эксперименталдық физика есептерінің толық мұрағатын қараңыз.',
    about_cta_btn: 'Барлық есептер',

    footer_tagline: 'Қазақстандағы эксперименталдық физика білімін дамыту.',
    footer_problems: 'Есептер мұрағаты',
    footer_copy: 'Қазақстандық эксперименталдық физика олимпиадасы',

    grade_prefix: 'Сынып',
    card_view: 'Есеп пен шешімді қарау',
    form_already_exists: 'Бұрыннан бар.',
    form_tab_edit: 'Өңдеу',
    form_tab_preview: 'Алдын ала қарау',
    form_lang_hint: 'Әр тіл үшін мазмұнды бөлек толтырыңыз',
    form_untitled: 'Атаусыз есеп',
    form_no_content: 'Мазмұн әлі жоқ…',
    form_back_editor: '← Редакторға қайту',
    form_remove_name: 'Жою',
  },
} as const;

export type TranslationKey = keyof typeof translations.en;

// ── Context ───────────────────────────────────────────────────────────────────

interface LangContextType {
  lang: Language;
  setLang: (l: Language) => void;
  t: (key: TranslationKey) => string;
}

const LangContext = createContext<LangContextType | null>(null);
const STORAGE_KEY = 'kazepho_lang';

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Language>(() => {
    const stored = localStorage.getItem(STORAGE_KEY) as Language | null;
    return stored && ['en', 'ru', 'kz'].includes(stored) ? stored : 'en';
  });

  const setLang = (l: Language) => {
    setLangState(l);
    localStorage.setItem(STORAGE_KEY, l);
  };

  const t = (key: TranslationKey): string => {
    const dict = translations[lang] as Record<string, string>;
    return dict[key] ?? (translations.en as Record<string, string>)[key] ?? key;
  };

  return <LangContext.Provider value={{ lang, setLang, t }}>{children}</LangContext.Provider>;
}

export function useLanguage() {
  const ctx = useContext(LangContext);
  if (!ctx) throw new Error('useLanguage must be used inside LanguageProvider');
  return ctx;
}
