import { createContext, useContext, useState, ReactNode } from 'react';
import { Language } from '../types';

// ── Translations ──────────────────────────────────────────────────────────────

const translations = {
  en: {
    // Nav
    nav_home: 'Home',
    nav_problems: 'Problems',
    nav_about: 'About',
    nav_add: 'Add Problem',
    nav_signout: 'Sign Out',
    nav_admin: 'Admin',

    // Home
    home_eyebrow: 'Kazakhstan Experimental Physics Olympiad',
    home_hero_title_1: 'Master the Art of',
    home_hero_title_2: 'Experimental Physics',
    home_hero_desc: 'A curated archive of experimental physics problems from KazEPhO, Respa, and IZhO — with full LaTeX solutions, methodology, and experimental setups.',
    home_cta_browse: 'Browse Problems',
    home_cta_learn: 'Learn More',
    home_stat_problems: 'Problems',
    home_stat_olympiads: 'Olympiads',
    home_stat_students: 'Students',
    home_featured: 'Featured Problems',
    home_view_all: 'View All Problems',
    home_olympiad_title: 'The Olympiads',
    home_olympiad_desc_kazepho: 'The flagship national competition. Original problems designed by Kazakhstani educators.',
    home_olympiad_desc_respa: 'Republic-level competition covering a broad range of physics for grades 8–11.',
    home_olympiad_desc_izho: 'International competition hosted in Almaty, known for its challenging experimental rounds.',
    home_browse: 'Browse',

    // Problems page
    problems_title: 'Problems Archive',
    problems_subtitle: 'Browse experimental physics problems. Press',
    problems_subtitle2: 'to search.',
    problems_empty_title: 'No problems found',
    problems_empty_desc: 'Try adjusting your filters or search term.',
    problems_clear_filters: 'Clear all filters',

    // Filter bar
    filter_search_placeholder: 'Search by title or topic…',
    filter_results: 'result',
    filter_results_plural: 'results',
    filter_clear_all: 'Clear all',
    filter_olympiad: 'Olympiad',
    filter_difficulty: 'Difficulty',
    filter_year: 'Year',
    filter_grade: 'Grade',
    filter_all: 'All',
    filter_all_years: 'All years',
    filter_all_grades: 'All grades',

    // Problem detail
    detail_all_problems: 'All Problems',
    detail_print: 'Print / Save PDF',
    detail_download_pdf: 'Download PDF',
    detail_share: 'Share',
    detail_copied: '✓ Copied!',
    detail_edit: 'Edit',
    detail_delete: 'Delete',
    detail_deleting: 'Deleting…',
    detail_statement: 'Problem Statement',
    detail_setup: 'Experimental Setup',
    detail_solution: 'Full Solution',
    detail_reveal: 'Reveal Solution',
    detail_hide: 'Hide Solution',
    detail_info: 'Problem Info',
    detail_olympiad: 'Olympiad',
    detail_year: 'Year',
    detail_difficulty: 'Difficulty',
    detail_grade: 'Grade',
    detail_topics: 'Topics',
    detail_language: 'Language',
    detail_more_from: 'More from',
    detail_not_found_title: 'Problem Not Found',
    detail_not_found_desc: "This problem doesn't exist or may have been removed.",
    detail_browse_all: 'Browse All Problems',
    detail_go_back: 'Go Back',
    detail_delete_confirm: 'Delete this problem permanently?',

    // Add/Edit problem
    add_title: 'Add New Problem',
    edit_title: 'Edit Problem',
    add_breadcrumb: 'Add Problem',
    edit_breadcrumb: 'Edit Problem',
    form_details: 'Problem Details',
    form_title_label: 'Title',
    form_title_placeholder: 'e.g., Measuring Speed of Sound',
    form_olympiad: 'Olympiad',
    form_add_olympiad: 'Add',
    form_cancel_olympiad: 'Cancel',
    form_olympiad_placeholder: 'e.g., Zhautykov',
    form_year: 'Year',
    form_grade: 'Grade',
    form_grade_na: 'N/A',
    form_difficulty: 'Difficulty',
    form_tags: 'Tags (comma-separated)',
    form_tags_placeholder: 'optics, waves, measurement',
    form_language: 'Problem Language',
    form_pdf: 'Upload PDF',
    form_pdf_hint: 'Upload a PDF version of this problem for download.',
    form_pdf_uploaded: 'PDF uploaded',
    form_pdf_remove: 'Remove',
    form_statement: 'Problem Statement',
    form_setup: 'Experimental Setup',
    form_solution: 'Full Solution',
    form_cancel: 'Cancel',
    form_save: 'Save Changes',
    form_add: 'Add Problem',
    form_saving: 'Saving…',
    form_saved: 'Changes saved!',
    form_added: 'Problem added!',
    form_redirecting: 'Redirecting…',
    form_unauthorized_title: 'Admin Access Required',
    form_unauthorized_desc: 'You must be signed in as an admin to manage problems.',
    form_sign_in: 'Sign In as Admin',
    editor_tip: 'Tip: Use',
    editor_tip2: 'for inline math,',
    editor_tip3: 'for display equations',
    editor_upload_image: 'Upload Image',
    editor_uploading: 'Uploading…',

    // About
    about_title: 'About KazEPhO',
    about_subtitle: 'Preserving and sharing experimental physics knowledge across Kazakhstan.',
    about_mission: 'Our Mission',
    about_mission_text: 'KazEPhO is a platform dedicated to making experimental physics problems accessible to all students. We archive problems from the most prestigious Kazakhstani and international olympiads.',
    about_olympiad_title: 'The Olympiads',
    about_history: 'History',
    about_platform: 'The Platform',
    about_platform_text: 'Built to be a living archive — problems can be updated, solutions refined, and new content added without touching the source code.',

    // Login
    login_title: 'Admin Access',
    login_subtitle: 'Enter the admin password to manage problems.',
    login_password: 'Password',
    login_show: 'Show password',
    login_hide: 'Hide password',
    login_submit: 'Sign In',
    login_signing: 'Signing in…',
    login_error: 'Incorrect password. Please try again.',
    login_back: '← Back to site',

    // Language names
    lang_en: 'English',
    lang_ru: 'Русский',
    lang_kz: 'Қазақша',

    // Language badge
    lang_badge_en: 'EN',
    lang_badge_ru: 'RU',
    lang_badge_kz: 'KZ',
  },

  ru: {
    nav_home: 'Главная',
    nav_problems: 'Задачи',
    nav_about: 'О проекте',
    nav_add: 'Добавить задачу',
    nav_signout: 'Выйти',
    nav_admin: 'Войти',

    home_eyebrow: 'Казахстанская Олимпиада по Экспериментальной Физике',
    home_hero_title_1: 'Овладейте искусством',
    home_hero_title_2: 'Экспериментальной Физики',
    home_hero_desc: 'Архив задач по экспериментальной физике из KazEPhO, Respa и ИЖО — с полными решениями на LaTeX, методологией и описаниями установок.',
    home_cta_browse: 'Смотреть задачи',
    home_cta_learn: 'Узнать больше',
    home_stat_problems: 'Задачи',
    home_stat_olympiads: 'Олимпиады',
    home_stat_students: 'Ученики',
    home_featured: 'Избранные задачи',
    home_view_all: 'Все задачи',
    home_olympiad_title: 'Олимпиады',
    home_olympiad_desc_kazepho: 'Главная национальная олимпиада. Оригинальные задачи казахстанских педагогов.',
    home_olympiad_desc_respa: 'Республиканская олимпиада по физике для 8–11 классов.',
    home_olympiad_desc_izho: 'Международная олимпиада в Алматы с известными экспериментальными турами.',
    home_browse: 'Смотреть',

    problems_title: 'Архив задач',
    problems_subtitle: 'Просматривайте задачи. Нажмите',
    problems_subtitle2: 'для поиска.',
    problems_empty_title: 'Задачи не найдены',
    problems_empty_desc: 'Попробуйте изменить фильтры или поисковый запрос.',
    problems_clear_filters: 'Сбросить фильтры',

    filter_search_placeholder: 'Поиск по названию или теме…',
    filter_results: 'результат',
    filter_results_plural: 'результатов',
    filter_clear_all: 'Сбросить',
    filter_olympiad: 'Олимпиада',
    filter_difficulty: 'Сложность',
    filter_year: 'Год',
    filter_grade: 'Класс',
    filter_all: 'Все',
    filter_all_years: 'Все годы',
    filter_all_grades: 'Все классы',

    detail_all_problems: 'Все задачи',
    detail_print: 'Печать / PDF',
    detail_download_pdf: 'Скачать PDF',
    detail_share: 'Поделиться',
    detail_copied: '✓ Скопировано!',
    detail_edit: 'Редактировать',
    detail_delete: 'Удалить',
    detail_deleting: 'Удаление…',
    detail_statement: 'Условие задачи',
    detail_setup: 'Экспериментальная установка',
    detail_solution: 'Полное решение',
    detail_reveal: 'Показать решение',
    detail_hide: 'Скрыть решение',
    detail_info: 'Информация о задаче',
    detail_olympiad: 'Олимпиада',
    detail_year: 'Год',
    detail_difficulty: 'Сложность',
    detail_grade: 'Класс',
    detail_topics: 'Темы',
    detail_language: 'Язык',
    detail_more_from: 'Ещё из',
    detail_not_found_title: 'Задача не найдена',
    detail_not_found_desc: 'Эта задача не существует или была удалена.',
    detail_browse_all: 'Все задачи',
    detail_go_back: 'Назад',
    detail_delete_confirm: 'Удалить задачу навсегда?',

    add_title: 'Добавить задачу',
    edit_title: 'Редактировать задачу',
    add_breadcrumb: 'Добавить задачу',
    edit_breadcrumb: 'Редактировать',
    form_details: 'Детали задачи',
    form_title_label: 'Название',
    form_title_placeholder: 'напр., Измерение скорости звука',
    form_olympiad: 'Олимпиада',
    form_add_olympiad: 'Добавить',
    form_cancel_olympiad: 'Отмена',
    form_olympiad_placeholder: 'напр., Жауытыков',
    form_year: 'Год',
    form_grade: 'Класс',
    form_grade_na: 'Н/П',
    form_difficulty: 'Сложность',
    form_tags: 'Теги (через запятую)',
    form_tags_placeholder: 'оптика, волны, измерения',
    form_language: 'Язык задачи',
    form_pdf: 'Загрузить PDF',
    form_pdf_hint: 'Загрузите PDF-версию задачи для скачивания.',
    form_pdf_uploaded: 'PDF загружен',
    form_pdf_remove: 'Удалить',
    form_statement: 'Условие задачи',
    form_setup: 'Экспериментальная установка',
    form_solution: 'Полное решение',
    form_cancel: 'Отмена',
    form_save: 'Сохранить',
    form_add: 'Добавить задачу',
    form_saving: 'Сохранение…',
    form_saved: 'Изменения сохранены!',
    form_added: 'Задача добавлена!',
    form_redirecting: 'Перенаправление…',
    form_unauthorized_title: 'Требуется доступ администратора',
    form_unauthorized_desc: 'Вы должны войти как администратор для управления задачами.',
    form_sign_in: 'Войти как администратор',
    editor_tip: 'Подсказка: используйте',
    editor_tip2: 'для инлайн-формул,',
    editor_tip3: 'для блочных формул',
    editor_upload_image: 'Загрузить изображение',
    editor_uploading: 'Загрузка…',

    about_title: 'О KazEPhO',
    about_subtitle: 'Сохранение и распространение знаний по экспериментальной физике в Казахстане.',
    about_mission: 'Наша миссия',
    about_mission_text: 'KazEPhO — платформа для доступа к задачам по экспериментальной физике для всех учеников. Мы архивируем задачи из самых престижных казахстанских и международных олимпиад.',
    about_olympiad_title: 'Олимпиады',
    about_history: 'История',
    about_platform: 'Платформа',
    about_platform_text: 'Создана как живой архив — задачи можно обновлять, решения улучшать, а новый контент добавлять без изменения исходного кода.',

    login_title: 'Вход для администратора',
    login_subtitle: 'Введите пароль администратора для управления задачами.',
    login_password: 'Пароль',
    login_show: 'Показать пароль',
    login_hide: 'Скрыть пароль',
    login_submit: 'Войти',
    login_signing: 'Вход…',
    login_error: 'Неверный пароль. Попробуйте ещё раз.',
    login_back: '← На сайт',

    lang_en: 'English',
    lang_ru: 'Русский',
    lang_kz: 'Қазақша',
    lang_badge_en: 'EN',
    lang_badge_ru: 'RU',
    lang_badge_kz: 'KZ',
  },

  kz: {
    nav_home: 'Басты бет',
    nav_problems: 'Есептер',
    nav_about: 'Жоба туралы',
    nav_add: 'Есеп қосу',
    nav_signout: 'Шығу',
    nav_admin: 'Кіру',

    home_eyebrow: 'Қазақстандық Эксперименталдық Физика Олимпиадасы',
    home_hero_title_1: 'Өнерін меңгеріңіз',
    home_hero_title_2: 'Эксперименталдық Физика',
    home_hero_desc: 'KazEPhO, Respa және ЖОлимпиадаларынан эксперименталдық физика есептерінің мұрағаты — толық LaTeX шешімдерімен, әдістемемен және тәжірибелік орнатулармен.',
    home_cta_browse: 'Есептерді қарау',
    home_cta_learn: 'Толығырақ',
    home_stat_problems: 'Есептер',
    home_stat_olympiads: 'Олимпиадалар',
    home_stat_students: 'Оқушылар',
    home_featured: 'Таңдаулы есептер',
    home_view_all: 'Барлық есептер',
    home_olympiad_title: 'Олимпиадалар',
    home_olympiad_desc_kazepho: 'Негізгі ұлттық олимпиада. Қазақстандық педагогтардың түпнұсқа есептері.',
    home_olympiad_desc_respa: '8–11 сынып оқушылары үшін республикалық физика олимпиадасы.',
    home_olympiad_desc_izho: 'Алматыда өтетін халықаралық олимпиада, тәжірибелік турлармен белгілі.',
    home_browse: 'Қарау',

    problems_title: 'Есептер мұрағаты',
    problems_subtitle: 'Есептерді қараңыз. Іздеу үшін',
    problems_subtitle2: 'басыңыз.',
    problems_empty_title: 'Есептер табылмады',
    problems_empty_desc: 'Сүзгілерді немесе іздеу сұрауын өзгертіп көріңіз.',
    problems_clear_filters: 'Сүзгілерді тазалау',

    filter_search_placeholder: 'Тақырып немесе тақырыбы бойынша іздеу…',
    filter_results: 'нәтиже',
    filter_results_plural: 'нәтиже',
    filter_clear_all: 'Тазалау',
    filter_olympiad: 'Олимпиада',
    filter_difficulty: 'Қиындық',
    filter_year: 'Жыл',
    filter_grade: 'Сынып',
    filter_all: 'Барлығы',
    filter_all_years: 'Барлық жылдар',
    filter_all_grades: 'Барлық сыныптар',

    detail_all_problems: 'Барлық есептер',
    detail_print: 'Басып шығару / PDF',
    detail_download_pdf: 'PDF жүктеу',
    detail_share: 'Бөлісу',
    detail_copied: '✓ Көшірілді!',
    detail_edit: 'Өңдеу',
    detail_delete: 'Жою',
    detail_deleting: 'Жойылуда…',
    detail_statement: 'Есеп шарты',
    detail_setup: 'Тәжірибелік орнату',
    detail_solution: 'Толық шешім',
    detail_reveal: 'Шешімді көрсету',
    detail_hide: 'Шешімді жасыру',
    detail_info: 'Есеп туралы ақпарат',
    detail_olympiad: 'Олимпиада',
    detail_year: 'Жыл',
    detail_difficulty: 'Қиындық',
    detail_grade: 'Сынып',
    detail_topics: 'Тақырыптар',
    detail_language: 'Тіл',
    detail_more_from: 'Қосымша:',
    detail_not_found_title: 'Есеп табылмады',
    detail_not_found_desc: 'Бұл есеп жоқ немесе жойылған болуы мүмкін.',
    detail_browse_all: 'Барлық есептер',
    detail_go_back: 'Артқа',
    detail_delete_confirm: 'Есепті біржолата жою керек пе?',

    add_title: 'Жаңа есеп қосу',
    edit_title: 'Есепті өңдеу',
    add_breadcrumb: 'Есеп қосу',
    edit_breadcrumb: 'Өңдеу',
    form_details: 'Есеп мәліметтері',
    form_title_label: 'Атауы',
    form_title_placeholder: 'мыс., Дыбыс жылдамдығын өлшеу',
    form_olympiad: 'Олимпиада',
    form_add_olympiad: 'Қосу',
    form_cancel_olympiad: 'Болдырмау',
    form_olympiad_placeholder: 'мыс., Жауытыков',
    form_year: 'Жыл',
    form_grade: 'Сынып',
    form_grade_na: 'Жоқ',
    form_difficulty: 'Қиындық',
    form_tags: 'Тегтер (үтірмен бөлінген)',
    form_tags_placeholder: 'оптика, толқындар, өлшем',
    form_language: 'Есеп тілі',
    form_pdf: 'PDF жүктеу',
    form_pdf_hint: 'Есептің PDF нұсқасын жүктеңіз.',
    form_pdf_uploaded: 'PDF жүктелді',
    form_pdf_remove: 'Жою',
    form_statement: 'Есеп шарты',
    form_setup: 'Тәжірибелік орнату',
    form_solution: 'Толық шешім',
    form_cancel: 'Болдырмау',
    form_save: 'Сақтау',
    form_add: 'Есеп қосу',
    form_saving: 'Сақталуда…',
    form_saved: 'Өзгерістер сақталды!',
    form_added: 'Есеп қосылды!',
    form_redirecting: 'Бағытталуда…',
    form_unauthorized_title: 'Әкімші рұқсаты қажет',
    form_unauthorized_desc: 'Есептерді басқару үшін әкімші ретінде кіруіңіз керек.',
    form_sign_in: 'Әкімші ретінде кіру',
    editor_tip: 'Кеңес:',
    editor_tip2: 'инлайн формула үшін,',
    editor_tip3: 'блок формула үшін',
    editor_upload_image: 'Сурет жүктеу',
    editor_uploading: 'Жүктелуде…',

    about_title: 'KazEPhO туралы',
    about_subtitle: 'Қазақстандағы эксперименталдық физика білімін сақтау және тарату.',
    about_mission: 'Біздің миссия',
    about_mission_text: 'KazEPhO — барлық оқушыларға эксперименталдық физика есептерін қолжетімді ету платформасы.',
    about_olympiad_title: 'Олимпиадалар',
    about_history: 'Тарих',
    about_platform: 'Платформа',
    about_platform_text: 'Тірі мұрағат ретінде жасалған — бастапқы кодты өзгертпестен есептерді жаңартуға болады.',

    login_title: 'Әкімші кірісі',
    login_subtitle: 'Есептерді басқару үшін әкімші құпия сөзін енгізіңіз.',
    login_password: 'Құпия сөз',
    login_show: 'Құпия сөзді көрсету',
    login_hide: 'Жасыру',
    login_submit: 'Кіру',
    login_signing: 'Кіруде…',
    login_error: 'Қате құпия сөз. Қайтадан көріңіз.',
    login_back: '← Сайтқа',

    lang_en: 'English',
    lang_ru: 'Русский',
    lang_kz: 'Қазақша',
    lang_badge_en: 'EN',
    lang_badge_ru: 'RU',
    lang_badge_kz: 'KZ',
  },
} as const;

export type TranslationKey = keyof typeof translations.en;

// ── Context ───────────────────────────────────────────────────────────────────

interface LangContextType {
  lang: Language;
  setLang: (l: Language) => void;
  t: (key: TranslationKey) => string;
}

const LangContext = createContext<LangContextType | null>(null);
const STORAGE_KEY = 'kazepho_lang';

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Language>(() => {
    const stored = localStorage.getItem(STORAGE_KEY) as Language | null;
    return stored && ['en', 'ru', 'kz'].includes(stored) ? stored : 'en';
  });

  const setLang = (l: Language) => {
    setLangState(l);
    localStorage.setItem(STORAGE_KEY, l);
  };

  const t = (key: TranslationKey): string => {
    const dict = translations[lang] as Record<string, string>;
    return dict[key] ?? (translations.en as Record<string, string>)[key] ?? key;
  };

  return <LangContext.Provider value={{ lang, setLang, t }}>{children}</LangContext.Provider>;
}

export function useLanguage() {
  const ctx = useContext(LangContext);
  if (!ctx) throw new Error('useLanguage must be used inside LanguageProvider');
  return ctx;
}
